kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: istio-example
  namespace: default
spec:
  hosts:
    - istio-example.kingbj0429.com
  gateways:
    - istio-system/default
  http:
    - route:
        - destination:
            host: istio-example
            subset: stable
          weight: 100
---
kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: istio-example
  namespace: default
spec:
  host: istio-example
  subsets:
    - name: stable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-example
  labels:
    app: istio-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-example
  template:
    metadata:
      labels:
        app: istio-example
    spec:
      containers:
        - name: istio-example
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: istio-example
spec:
  selector:
    app: istio-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
