apiVersion: v1
data:
  #-- Harbor Core
  secret: "PGVrcy9oYXJib3Ivc2VjcmVydD4="
  secretKey: "PGVrcy9oYXJib3Ivc2VjcmVydC1rZXk+"

  #-- Harbor Admin
  HARBOR_ADMIN_PASSWORD: "PGVrcy9oYXJib3IvYWRtaW4tcGFzc3dvcmQ+"

  #-- JobService
  JOBSERVICE_SECRET: "PGVrcy9oYXJib3Ivam9ic2VydmljZS1zZWNyZXQ+"

  #-- Registry
  REGISTRY_HTTP_SECRET: "PGVrcy9oYXJib3IvcmVnaXN0cnktaHR0cC1zZWNyZXQ+"
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: dev-secrets-manager
  name: harbor-credentials
  namespace: storage-system
type: Opaque
